### ISSUE TITLE
Fixing Mac_sag9_2

### ISSUE THREAD

**Issue by mohannedkhairy** [3-manifolds/fix_mac_sage#2]
hello, 

I think I have an issue similar to the closed one,I ve downloaded fix_mac_sage9_2.tar to fix the ssl issue with Sage 9.2 on Mac OS X Big Sur, after running the fix.py without renaming it the patch runs and start patching but end with this error message. 
trying to run it again only gives this error message.

```
base) mohannedkhairy@Mohanneds-MacBook-Pro Downloads %  /Applications/SageMath-9.2.app/sage -python -m fix.py             
/Applications/SageMath-9.2.app/Contents/Resources/sage/local/bin/python3: Error while finding module specification for 'fix.py' (ModuleNotFoundError: No module named 'fix')
```

**Comment by culler** [comment]
The sage python interpreter is telling you that it cannot find the module fix.py.  In order for it to find that module you either need to have fix.py in your current working directory when you run sage -python or to  set your PYTHONPATH environment variable to the directory containing fix.py.

**Comment by NathanDunfield** [comment]
If the ``fix_mac_sage9_2`` folder is in ``Downloads``, then you need to do:
```
cd ~/Downloads
/Applications/SageMath-9.2.app/sage -python -m fix_mac_sage9_2.fix
```
Note that it is `fix_mac_sage9_2.fix` at the end, not `fix.py`.

**Comment by mohannedkhairy** [comment]
> If the `fix_mac_sage9_2` folder is in `Downloads`, then you need to do:
> 
> ```
> cd ~/Downloads
> /Applications/SageMath-9.2.app/sage -python -m fix_mac_sage9_2.fix
> ```
> 
> Note that it is `fix_mac_sage9_2.fix` at the end, not `fix.py`.

This fixed my issue, I was trying to act from the file. Thank you. !

**Comment by culler** [comment]
Thank you Nathan.  Much clearer.  And it is definitely better to use the fixer as it was designed to be used!
